name=TCA6424A
version=0.1.0
author=Wenzy
maintainer=Wenzy
sentence=Arduino library for TCA6424A 24-bit I2C GPIO expander
paragraph=Arduino library for TCA6424A (Remote 24-bit I2C and SMBus I/O Expander with Interrupt Output and Configuration Registers)
category=Device Control
url=https://github.com/wzy-github123/TCA6424A
architectures=*
